##### 1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [7]:
import numpy as np

tekBoyut=np.array([1,2,3,4,5], dtype=int)

##### 2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım. 

İki boyutlu array:
[[1,2,6,7],
 [4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]]

 

In [8]:
ikiBoyut = np.array([[1,2,6,7],[4,3,9,5]], dtype=int)
ucBoyut = np.array([[[7,5,14],[21,8,11]],[[8,6,20],[14,3,9]]], dtype=int)

##### 3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım

In [13]:
#İki boyutlu arraydaki 2 elemanına ulaşalım
eleman=ikiBoyut[0,1]
print(eleman)

2


In [14]:
#İki boyutlu arraydaki 7 elemanına ulaşalım
eleman=ikiBoyut[0,-1]
print(eleman)

7


In [16]:
#Üç boyutlu arraydaki 9 elemanına ulaşalım
eleman=ucBoyut[-1,-1,-1]
print(eleman)

9


In [18]:
#Üç boyutlu arraydaki 5 elemanına ulaşalım
eleman=ucBoyut[0,0,1]
print(eleman)


5


##### 4. Arrayler üzerinde slicing işlemi uygulayalım.

In [19]:
#İki boyutlu arraydaki 2,6 elemanlarına ulaşalım
eleman=ikiBoyut[0,1:3]
print(eleman)

[2 6]


In [20]:
#İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım
eleman=ikiBoyut[-1,1:4]
print(eleman)

[3 9 5]


In [21]:
#Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım
eleman=ucBoyut[0,1]
print(eleman)

[21  8 11]


In [22]:
#Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım
eleman=ucBoyut[-1,0,1:3]
print(eleman)

[ 6 20]


##### 5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [31]:
sifirlar=np.zeros((5,3), dtype=int)
print(sifirlar)
birler=np.ones((5,3),dtype=int)
print("*********")
print(birler)
print("*********")
satirBirles=np.vstack((sifirlar,birler))
sutunBirles=np.hstack((sifirlar,birler))
print(satirBirles)
print("*********")
print(sutunBirles)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
*********
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
*********
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
*********
[[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
